/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as OcorrenciaIdRouteImport } from './routes/ocorrencia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciaIdRoute = OcorrenciaIdRouteImport.update({
  id: '/ocorrencia/$id',
  path: '/ocorrencia/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRoute
  '/mapa': typeof MapaRoute
  '/ocorrencia/$id': typeof OcorrenciaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRoute
  '/mapa': typeof MapaRoute
  '/ocorrencia/$id': typeof OcorrenciaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRoute
  '/mapa': typeof MapaRoute
  '/ocorrencia/$id': typeof OcorrenciaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buscar' | '/dashboard' | '/mapa' | '/ocorrencia/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buscar' | '/dashboard' | '/mapa' | '/ocorrencia/$id'
  id: '__root__' | '/' | '/buscar' | '/dashboard' | '/mapa' | '/ocorrencia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  DashboardRoute: typeof DashboardRoute
  MapaRoute: typeof MapaRoute
  OcorrenciaIdRoute: typeof OcorrenciaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencia/$id': {
      id: '/ocorrencia/$id'
      path: '/ocorrencia/$id'
      fullPath: '/ocorrencia/$id'
      preLoaderRoute: typeof OcorrenciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  DashboardRoute: DashboardRoute,
  MapaRoute: MapaRoute,
  OcorrenciaIdRoute: OcorrenciaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
