/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedAnimalEncontradoRouteImport } from './routes/_authenticated/animal-encontrado'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedMeusAnimaisRouteImport } from './routes/_authenticated/meus-animais'
import { Route as AuthenticatedMinhasOcorrenciasRouteImport } from './routes/_authenticated/minhas-ocorrencias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedNovaOcorrenciaRouteImport } from './routes/_authenticated/nova-ocorrencia'
import { Route as AuthenticatedNovoAvistamentoRouteImport } from './routes/_authenticated/novo-avistamento'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminDenunciasRouteImport } from './routes/_authenticated/admin.denuncias'
import { Route as AuthenticatedAdminOcorrenciasRouteImport } from './routes/_authenticated/admin.ocorrencias'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedOcorrenciaIdRouteImport } from './routes/_authenticated/ocorrencia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnimalEncontradoRoute =
  AuthenticatedAnimalEncontradoRouteImport.update({
    id: '/_authenticated/animal-encontrado',
    path: '/animal-encontrado',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/_authenticated/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/_authenticated/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusAnimaisRoute =
  AuthenticatedMeusAnimaisRouteImport.update({
    id: '/_authenticated/meus-animais',
    path: '/meus-animais',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMinhasOcorrenciasRoute =
  AuthenticatedMinhasOcorrenciasRouteImport.update({
    id: '/_authenticated/minhas-ocorrencias',
    path: '/minhas-ocorrencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/_authenticated/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNovaOcorrenciaRoute =
  AuthenticatedNovaOcorrenciaRouteImport.update({
    id: '/_authenticated/nova-ocorrencia',
    path: '/nova-ocorrencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNovoAvistamentoRoute =
  AuthenticatedNovoAvistamentoRouteImport.update({
    id: '/_authenticated/novo-avistamento',
    path: '/novo-avistamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/_authenticated/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/_authenticated/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDenunciasRoute =
  AuthenticatedAdminDenunciasRouteImport.update({
    id: '/_authenticated/admin/denuncias',
    path: '/admin/denuncias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOcorrenciasRoute =
  AuthenticatedAdminOcorrenciasRouteImport.update({
    id: '/_authenticated/admin/ocorrencias',
    path: '/admin/ocorrencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/_authenticated/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOcorrenciaIdRoute =
  AuthenticatedOcorrenciaIdRouteImport.update({
    id: '/_authenticated/ocorrencia/$id',
    path: '/ocorrencia/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/animal-encontrado': typeof AuthenticatedAnimalEncontradoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/meus-animais': typeof AuthenticatedMeusAnimaisRoute
  '/minhas-ocorrencias': typeof AuthenticatedMinhasOcorrenciasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ocorrencia': typeof AuthenticatedNovaOcorrenciaRoute
  '/novo-avistamento': typeof AuthenticatedNovoAvistamentoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/admin/ocorrencias': typeof AuthenticatedAdminOcorrenciasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/ocorrencia/$id': typeof AuthenticatedOcorrenciaIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/animal-encontrado': typeof AuthenticatedAnimalEncontradoRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/meus-animais': typeof AuthenticatedMeusAnimaisRoute
  '/minhas-ocorrencias': typeof AuthenticatedMinhasOcorrenciasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ocorrencia': typeof AuthenticatedNovaOcorrenciaRoute
  '/novo-avistamento': typeof AuthenticatedNovoAvistamentoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/admin/ocorrencias': typeof AuthenticatedAdminOcorrenciasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/ocorrencia/$id': typeof AuthenticatedOcorrenciaIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/animal-encontrado': typeof AuthenticatedAnimalEncontradoRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/meus-animais': typeof AuthenticatedMeusAnimaisRoute
  '/_authenticated/minhas-ocorrencias': typeof AuthenticatedMinhasOcorrenciasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/nova-ocorrencia': typeof AuthenticatedNovaOcorrenciaRoute
  '/_authenticated/novo-avistamento': typeof AuthenticatedNovoAvistamentoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/denuncias': typeof AuthenticatedAdminDenunciasRoute
  '/_authenticated/admin/ocorrencias': typeof AuthenticatedAdminOcorrenciasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/ocorrencia/$id': typeof AuthenticatedOcorrenciaIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/login'
    | '/sobre'
    | '/animal-encontrado'
    | '/buscar'
    | '/dashboard'
    | '/mapa'
    | '/meus-animais'
    | '/minhas-ocorrencias'
    | '/notificacoes'
    | '/nova-ocorrencia'
    | '/novo-avistamento'
    | '/perfil'
    | '/admin/denuncias'
    | '/admin/ocorrencias'
    | '/admin/usuarios'
    | '/ocorrencia/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/login'
    | '/sobre'
    | '/animal-encontrado'
    | '/buscar'
    | '/dashboard'
    | '/mapa'
    | '/meus-animais'
    | '/minhas-ocorrencias'
    | '/notificacoes'
    | '/nova-ocorrencia'
    | '/novo-avistamento'
    | '/perfil'
    | '/admin/denuncias'
    | '/admin/ocorrencias'
    | '/admin/usuarios'
    | '/ocorrencia/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/login'
    | '/sobre'
    | '/_authenticated/animal-encontrado'
    | '/_authenticated/buscar'
    | '/_authenticated/dashboard'
    | '/_authenticated/mapa'
    | '/_authenticated/meus-animais'
    | '/_authenticated/minhas-ocorrencias'
    | '/_authenticated/notificacoes'
    | '/_authenticated/nova-ocorrencia'
    | '/_authenticated/novo-avistamento'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/denuncias'
    | '/_authenticated/admin/ocorrencias'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/ocorrencia/$id'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LoginRoute: typeof LoginRoute
  SobreRoute: typeof SobreRoute
  AuthenticatedAnimalEncontradoRoute: typeof AuthenticatedAnimalEncontradoRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMeusAnimaisRoute: typeof AuthenticatedMeusAnimaisRoute
  AuthenticatedMinhasOcorrenciasRoute: typeof AuthenticatedMinhasOcorrenciasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovaOcorrenciaRoute: typeof AuthenticatedNovaOcorrenciaRoute
  AuthenticatedNovoAvistamentoRoute: typeof AuthenticatedNovoAvistamentoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminDenunciasRoute: typeof AuthenticatedAdminDenunciasRoute
  AuthenticatedAdminOcorrenciasRoute: typeof AuthenticatedAdminOcorrenciasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedOcorrenciaIdRoute: typeof AuthenticatedOcorrenciaIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/animal-encontrado': {
      id: '/_authenticated/animal-encontrado'
      path: '/animal-encontrado'
      fullPath: '/animal-encontrado'
      preLoaderRoute: typeof AuthenticatedAnimalEncontradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-animais': {
      id: '/_authenticated/meus-animais'
      path: '/meus-animais'
      fullPath: '/meus-animais'
      preLoaderRoute: typeof AuthenticatedMeusAnimaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minhas-ocorrencias': {
      id: '/_authenticated/minhas-ocorrencias'
      path: '/minhas-ocorrencias'
      fullPath: '/minhas-ocorrencias'
      preLoaderRoute: typeof AuthenticatedMinhasOcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nova-ocorrencia': {
      id: '/_authenticated/nova-ocorrencia'
      path: '/nova-ocorrencia'
      fullPath: '/nova-ocorrencia'
      preLoaderRoute: typeof AuthenticatedNovaOcorrenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/novo-avistamento': {
      id: '/_authenticated/novo-avistamento'
      path: '/novo-avistamento'
      fullPath: '/novo-avistamento'
      preLoaderRoute: typeof AuthenticatedNovoAvistamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/denuncias': {
      id: '/_authenticated/admin/denuncias'
      path: '/admin/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AuthenticatedAdminDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/ocorrencias': {
      id: '/_authenticated/admin/ocorrencias'
      path: '/admin/ocorrencias'
      fullPath: '/admin/ocorrencias'
      preLoaderRoute: typeof AuthenticatedAdminOcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ocorrencia/$id': {
      id: '/_authenticated/ocorrencia/$id'
      path: '/ocorrencia/$id'
      fullPath: '/ocorrencia/$id'
      preLoaderRoute: typeof AuthenticatedOcorrenciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  LoginRoute: LoginRoute,
  SobreRoute: SobreRoute,
  AuthenticatedAnimalEncontradoRoute: AuthenticatedAnimalEncontradoRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMeusAnimaisRoute: AuthenticatedMeusAnimaisRoute,
  AuthenticatedMinhasOcorrenciasRoute: AuthenticatedMinhasOcorrenciasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovaOcorrenciaRoute: AuthenticatedNovaOcorrenciaRoute,
  AuthenticatedNovoAvistamentoRoute: AuthenticatedNovoAvistamentoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminDenunciasRoute: AuthenticatedAdminDenunciasRoute,
  AuthenticatedAdminOcorrenciasRoute: AuthenticatedAdminOcorrenciasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedOcorrenciaIdRoute: AuthenticatedOcorrenciaIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
